package dragoletinhos.view;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Monique
 */
public class TelaCachorro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCachorro
     */
    public TelaCachorro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabelNomeCachorro = new javax.swing.JLabel();
        jLabelSexo = new javax.swing.JLabel();
        jLabelIdade = new javax.swing.JLabel();
        jLabelPesoCachorro = new javax.swing.JLabel();
        jLabelPorte = new javax.swing.JLabel();
        jLabelRacaCachorro = new javax.swing.JLabel();
        jLabelTutorCachorro = new javax.swing.JLabel();
        jLabelAlimentCachorro = new javax.swing.JLabel();
        jLabelCastradoCachorro = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldNomeCachorro = new javax.swing.JTextField();
        jTextFieldIdadeCachorro = new javax.swing.JTextField();
        jTextFieldSexoCachorro = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextFieldPorte = new javax.swing.JTextField();
        jTextFieldTutorCachorro = new javax.swing.JTextField();
        jTextFieldRacaCachorro = new javax.swing.JTextField();
        jTextFieldAlimentCachorro = new javax.swing.JTextField();
        jComboBoxCachorro = new javax.swing.JComboBox<>();
        rbCachorroSim = new javax.swing.JRadioButton();
        rbCachorroNao = new javax.swing.JRadioButton();
        btVoltar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btCadastrar = new javax.swing.JButton();
        btInfo = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de cachorro");
        setIconImage(new ImageIcon(getClass().getResource("/dragoletinhos/imagens/patinha.png")).getImage()
        );
        setResizable(false);

        jLabelNomeCachorro.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelNomeCachorro.setForeground(new java.awt.Color(51, 87, 201));
        jLabelNomeCachorro.setText("Nome: ");

        jLabelSexo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelSexo.setForeground(new java.awt.Color(51, 87, 201));
        jLabelSexo.setText("Sexo:");

        jLabelIdade.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelIdade.setForeground(new java.awt.Color(51, 87, 201));
        jLabelIdade.setText("Idade:");

        jLabelPesoCachorro.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelPesoCachorro.setForeground(new java.awt.Color(51, 87, 201));
        jLabelPesoCachorro.setText("Peso: ");

        jLabelPorte.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelPorte.setForeground(new java.awt.Color(51, 87, 201));
        jLabelPorte.setText("Porte: ");

        jLabelRacaCachorro.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelRacaCachorro.setForeground(new java.awt.Color(51, 87, 201));
        jLabelRacaCachorro.setText("Raça: ");

        jLabelTutorCachorro.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelTutorCachorro.setForeground(new java.awt.Color(51, 87, 201));
        jLabelTutorCachorro.setText("Tutor:");

        jLabelAlimentCachorro.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelAlimentCachorro.setForeground(new java.awt.Color(51, 87, 201));
        jLabelAlimentCachorro.setText("Alimentação: ");

        jLabelCastradoCachorro.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelCastradoCachorro.setForeground(new java.awt.Color(51, 87, 201));
        jLabelCastradoCachorro.setText("Castrado: ");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 87, 201));
        jLabel10.setText("Adestrado: ");

        jTextFieldNomeCachorro.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jTextFieldNomeCachorro.setForeground(new java.awt.Color(51, 87, 201));
        jTextFieldNomeCachorro.setBorder(null);

        jTextFieldIdadeCachorro.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jTextFieldIdadeCachorro.setForeground(new java.awt.Color(51, 87, 201));
        jTextFieldIdadeCachorro.setBorder(null);

        jTextFieldSexoCachorro.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jTextFieldSexoCachorro.setForeground(new java.awt.Color(51, 87, 201));
        jTextFieldSexoCachorro.setBorder(null);

        jTextField4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(51, 87, 201));
        jTextField4.setBorder(null);

        jTextFieldPorte.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jTextFieldPorte.setForeground(new java.awt.Color(51, 87, 201));
        jTextFieldPorte.setBorder(null);

        jTextFieldTutorCachorro.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jTextFieldTutorCachorro.setForeground(new java.awt.Color(51, 87, 201));
        jTextFieldTutorCachorro.setBorder(null);

        jTextFieldRacaCachorro.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jTextFieldRacaCachorro.setForeground(new java.awt.Color(51, 87, 201));
        jTextFieldRacaCachorro.setBorder(null);

        jTextFieldAlimentCachorro.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jTextFieldAlimentCachorro.setForeground(new java.awt.Color(51, 87, 201));
        jTextFieldAlimentCachorro.setBorder(null);

        jComboBoxCachorro.setForeground(new java.awt.Color(51, 87, 201));
        jComboBoxCachorro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione ", "Sim", "Não" }));

        buttonGroup1.add(rbCachorroSim);
        rbCachorroSim.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rbCachorroSim.setForeground(new java.awt.Color(51, 87, 201));
        rbCachorroSim.setText("Sim");

        buttonGroup1.add(rbCachorroNao);
        rbCachorroNao.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rbCachorroNao.setForeground(new java.awt.Color(51, 87, 201));
        rbCachorroNao.setText("Não");

        btVoltar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btVoltar.setForeground(new java.awt.Color(51, 87, 201));
        btVoltar.setText("VOLTAR");
        btVoltar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 161, 228)));
        btVoltar.setContentAreaFilled(false);
        btVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btLimpar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btLimpar.setForeground(new java.awt.Color(51, 87, 201));
        btLimpar.setText("LIMPAR");
        btLimpar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 161, 228)));
        btLimpar.setContentAreaFilled(false);
        btLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btCadastrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btCadastrar.setForeground(new java.awt.Color(51, 87, 201));
        btCadastrar.setText("CADASTRAR");
        btCadastrar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 161, 228)));
        btCadastrar.setContentAreaFilled(false);
        btCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btInfo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btInfo.setForeground(new java.awt.Color(51, 87, 201));
        btInfo.setText("INFO");
        btInfo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 161, 228)));
        btInfo.setContentAreaFilled(false);
        btInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dragoletinhos/imagens/dog-nose.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jLabel11)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelPorte)
                    .addComponent(jLabelSexo)
                    .addComponent(jLabelNomeCachorro)
                    .addComponent(jLabelIdade)
                    .addComponent(jLabelPesoCachorro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNomeCachorro)
                    .addComponent(jTextFieldSexoCachorro)
                    .addComponent(jTextFieldIdadeCachorro)
                    .addComponent(jTextField4)
                    .addComponent(jTextFieldPorte, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAlimentCachorro)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelTutorCachorro)
                        .addComponent(jLabelRacaCachorro))
                    .addComponent(jLabelCastradoCachorro, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rbCachorroSim)
                    .addComponent(rbCachorroNao)
                    .addComponent(jTextFieldTutorCachorro)
                    .addComponent(jTextFieldRacaCachorro)
                    .addComponent(jTextFieldAlimentCachorro)
                    .addComponent(jComboBoxCachorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTutorCachorro)
                            .addComponent(jTextFieldTutorCachorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelRacaCachorro)
                            .addComponent(jTextFieldRacaCachorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAlimentCachorro)
                            .addComponent(jTextFieldAlimentCachorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCastradoCachorro)
                            .addComponent(jComboBoxCachorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(rbCachorroSim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbCachorroNao))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNomeCachorro)
                            .addComponent(jTextFieldNomeCachorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSexo)
                            .addComponent(jTextFieldSexoCachorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelIdade)
                            .addComponent(jTextFieldIdadeCachorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPesoCachorro)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPorte)
                            .addComponent(jTextFieldPorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCachorro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCachorro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCachorro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCachorro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCachorro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btInfo;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jComboBoxCachorro;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabelAlimentCachorro;
    private javax.swing.JLabel jLabelCastradoCachorro;
    private javax.swing.JLabel jLabelIdade;
    private javax.swing.JLabel jLabelNomeCachorro;
    private javax.swing.JLabel jLabelPesoCachorro;
    private javax.swing.JLabel jLabelPorte;
    private javax.swing.JLabel jLabelRacaCachorro;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelTutorCachorro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextFieldAlimentCachorro;
    private javax.swing.JTextField jTextFieldIdadeCachorro;
    private javax.swing.JTextField jTextFieldNomeCachorro;
    private javax.swing.JTextField jTextFieldPorte;
    private javax.swing.JTextField jTextFieldRacaCachorro;
    private javax.swing.JTextField jTextFieldSexoCachorro;
    private javax.swing.JTextField jTextFieldTutorCachorro;
    private javax.swing.JRadioButton rbCachorroNao;
    private javax.swing.JRadioButton rbCachorroSim;
    // End of variables declaration//GEN-END:variables
}
